reggie:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: reggie2
    username: root
    password: 1234
  redis:
    host: localhost
    port: 6379
    database: 5
    password: 123456
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: ****
    access-key-secret: ****
    bucket-name: reggie-jay-astro
  wechat:
    appid: wxe68f033026b541d2
    secret: ****
